apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
  labels:
    app: notification
    project: microservices_mp4-to-mp3-converter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
        project: microservices_mp4-to-mp3-converter
    spec:
      containers:
      - name: notification
        image: adityadocs/notification-microservices1:latest
        resources:
          requests:
            memory: "64Mi"
            cpu: "25m"
          limits:
            memory: "64Mi"
            cpu: "80m"
        envFrom:
          - secretRef:
              name: notication-email-secret
          - configMapRef:
              name: notification-cm
