apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rabbitmq-secret
  namespace: default
spec:
  encryptedData:
    DATA: AgBHJndr1HLt333qMl4Kuu/5fvemKQPLdKNduh+CVzoVLXbJ2FOMWNBIGpCwHHPYRQJPqnyP4unP0FCkqgMdthnggs8bsNMfc5o4mwg7dCpWfF9f+173mevhS2F7q3cNOob/DwkqQkhY/EMB8gyhe3bUvmodOj2V4fyCG9NFlHUPoSdWuaj5DksLTUanrffpUx715agHAfKdTPoVYJoIhvZpVVL4nLo9BlqLq0/oYwiXkzrYDP5mmJSXMYRDIWOPMzehCuNtxuItVH+IkAkXnOssR8COYKAy4UGWjCjm8HUKp+OX5CEZ5EzCsSI/UbJ3UYymblrbFBP7UFEIiY0yonmLrOCcHUgYIGtiNOo+OM1MHj6yi23WKzB8q+DYmGS8JnTaYwyCtKE0yRifoVfZlVROEHExIE8dtalKXOrEz0EIrCMBtKraudbaT82R/8sIGFzbciBcfdF3s7arOmoE2iOUAy7/y1Ve878CbsZkFuHrpe/nRpZu9nkWnWMK2wbfDWUGzvuPcGBV9Q9A5xknkzO3ycxX40rMkKjOgdE8txWehOMyk0XjJAuAKaAGMXK01hqUg4+i2Jfkw5TJtkvrRoRT9rGkO9Fdj1xzF8ezyomOZPjsLWDxxJOlkWBBDRzZZ0dsxOrEKR/7STHvhV0+WPQYwxwVlNQry+QJ6rHOpVK9KK+KDglQQTz/2f68JR2tLYqVGP+MolIJ1wg35bnmUw==
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: rabbitmq
        project: microservices_mp4-to-mp3-converter
      name: rabbitmq-secret
      namespace: default
    type: Opaque

