apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysql-secret
  namespace: default
spec:
  encryptedData:
    MYSQL_DATABASE: AgAIm/JvGqlKlGRLo7IY2ZTT0NwxoDkNUWiWFfTotYZiyGVmZClA3J6AZU/9Ma3oL1JpPu2hGTartgyhmk1hfCi7Hx1Txo3jphkFzlg7jVW7Q2ODnxPype44mhVk9cIRyTnYzVbBNKeai+OXab1lFlW8aD49RprsfoMWwMkVMAi1pU+kFlV49ItWdxEiMw6Q6189HEpYjWeGhZVPTpqI+f0cINDL4RhNLTu1sehbXztXH58EBDF7ZE0wegdOFty8y0GjZZ2fkMWHIpxonRCtOfy1dIYETJ3e9WeoSy5WkvtAWCUmpWxp6F8GdU297F8hlXiqmiSUPFQXXdgvbuOY2JGeKU2U2f+/IHKkI6w4rhGEXPuZS2e3atJo7yYaXSgZgcbDgZhczsPXxmTNfVJQdR5w6ECcnAqyU7n/nvE7TPMo65oyrRFE8Xk70WJRGn/uLHBnK1uudULcZWg/hcqDYA4qj6jNk3+jc34gWes0xRInnu7QAeIfT6JS0j2q9bnfKIS8tcQg4/n/iTqmlvDZvQUPg0QNWaUb9qjH2Y+9y70EuecBVPpCY3JpXqXHIkKnSwjBchb/lvxi8IXsykmuX4auNeETCLdKlEn1QGhMlFM07ohkRo5UR6lL3640on7Ht48EqmK0YEAHclMKlNzyYYMzD5l/SpjGEv6e9TfCPF96i2/FYDrUXk30nkVPZ6P5T0HWQ7xu
    MYSQL_ROOT_PASSWORD: AgAgr2x7bhxcM5pQKaFIDN3TEW9skqFm/ib+adcsz8S9ueenDWOtkpnndeSW6dXh4ArWDMta2eh6DvLCvkPMfgBurz+/BRHn3zpWPjkbvGF7yKlE7OCu0PomfAxAKyNsSGgptN7wM2Zh8YKljXZ6zxIJm8UEpIhcdgjzgLK730RCM/gazyZwiAwY6BCLJHSOdEScZptO7CT4elV9AUYOCD1uxKzyPqlaEDz4WsQMDgO0H185gNEIAePW03X1ZfHhQf4Evhw02TkU2kVEBbwkKvHzGrBHRDd8XqZAMriop2paHNWSE4+Geo1ZMs5eHbsD6wMONT5zu16DiZdAP8b+SGqY+NRkbHh/qsIOEuhgZI2K5gWNAcxdDNMXauncOkK80Ek0l8YiJyF4m+RUT9zBTT07I/Zr05L30rffKTdlb6FkaELUZ1I/B1HTATMi7nmT9+pcUT3Pq+uNT7mRnrHABTHD5uQIJWtxtldNzBVWxxxP6XZZE2jAPRw3wPkKvU7yURnozrHqHl3gh4Y/cqJ6RCzxAr3J6Z3KQygKuDXSsVfuPlJAFaqEtIcfuGHHpvZIHbjHDs3UyFkFTPBeMYht38bsXNI3YXGymjk3/bdx4TEsL+6s05NgAdf3ZKDBOXN+NJJvZG+gvbh1TvcBJ4q8jTWdV05d/z614qiywIYdiCfP6wo521Td43NY47QiqDLXnMMVk1zv
  template:
    metadata:
      creationTimestamp: null
      labels:
        db: mysql
        project: microservices_mp4-to-mp3-converter
      name: mysql-secret
      namespace: default
    type: Opaque

