apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
    project: microservices_mp4-to-mp3-converter
spec:
  replicas: 1
  serviceName: "no-applicable"
  selector:
    matchLabels:
      app: rabbitmq
      project: microservices_mp4-to-mp3-converter
  template:
    metadata:
      labels:
        app: rabbitmq
        project: microservices_mp4-to-mp3-converter
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management
        ports:
        - containerPort: 15672
          name: http
          protocol: TCP
        - name: amqp   # advanced-message-queuing-protocol
          protocol: TCP
          containerPort: 5672
        envFrom:
          - configMapRef:
              name: rabbitmq-cm
          - secretRef:
              name: rabbitmq-secret
        resources:
          requests:
            cpu: "100m"
            memory: "400Mi"
          limits:
            cpu: "400m"
            memory: "800Mi"
        readinessProbe:
          exec: 
            command: ["rabbitmqadmin", "list", "vhosts"]
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 60
          

