---
- name: Install kubectl command line utility
  community.general.snap:
    name: kubectl
    state: present
    classic: yes
    channel: 1.30/stable

- name: Enable microk8s addons
  shell: |
    microk8s enable ingress
    microk8s enable dns
    microk8s enable hostpath-storage

- name: Add server IP to server cert
  ansible.builtin.lineinfile:
    path: /var/snap/microk8s/current/certs/csr.conf.template
    insertbefore: '^\#MOREIPS'
    line: "IP.100 = {{ ansible_host }}"
    state: present

- name: Cooldown for 5 seconds
  ansible.builtin.wait_for:
    timeout: 5

- name: Refresh server cert
  shell: microk8s refresh-certs -e ca.crt

- name: Create .kube directory
  ansible.builtin.file:
    path: "/home/ubuntu/.kube"
    state: directory
    mode: "0777"
    owner: ubuntu
    group: ubuntu

- name: Save kubeconfig to .kube/config
  shell: microk8s config > /home/ubuntu/.kube/config
  args:
    creates: "/home/ubuntu/.kube/config"

- name: Save kubeconfig to local
  run_once: true
  fetch: src=/home/ubuntu/.kube/config dest={{ playbook_dir }}/../kube/ flat=yes