apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    db: mongodb
    project: microservices_mp4-to-mp3-converter
spec:
  selector:
    db: mongodb
  ports:
  - port: 27017
  type: ClusterIP