apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  labels:
    app: auth
    project: microservices_mp4-to-mp3-converter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: adityadocs/auth-microservices1:latest
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: auth-cm
            - secretRef:
                name: auth-secret
          resources:
            requests:
              memory: "64Mi"
              cpu: "25m"
            limits:
              memory: "64Mi"
              cpu: "80m"