apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-cm
  labels:
    app: auth
    project: microservices_mp4-to-mp3-converter
data:
  MYSQL_HOST: mysql
  MYSQL_USER: root
  MYSQL_DB: auth
  MYSQL_PORT: "3306"