- name: Download and install Helm
  ansible.builtin.shell: |
    curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
  args:
    creates: /usr/local/bin/helm

- name: Verify Helm installation
  ansible.builtin.command:
    cmd: helm version
  register: helm_version_output

- name: Display Helm version
  ansible.builtin.debug:
    msg: "{{ helm_version_output.stdout }}"

- name: Install sealed secrets
  kubernetes.core.helm:
    release_name: sealed-secrets
    chart_ref: oci://registry-1.docker.io/bitnamicharts/sealed-secrets
    namespace: kube-system
    kubeconfig: /home/ubuntu/.kube/config
    
- name: Copy kubeseal certs
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/../keys/kubeseal/"
    dest: /home/ubuntu/.kube/kubeseal-certs/
    owner: ubuntu
    group: ubuntu
    mode: 0755

- name: Create kubeseal cert TLS secrets
  become: false
  shell: |
    kubectl -n kube-system create secret tls kubeseal-seal-secret --cert /home/ubuntu/.kube/kubeseal-certs/tls.crt --key /home/ubuntu/.kube/kubeseal-certs/tls.key

- name: Label kubeseal cert TLS secrets
  become: false
  shell: |
    kubectl -n kube-system label secret kubeseal-seal-secret sealedsecrets.bitnami.com/sealed-secrets-key=active
  
- name: Refresh kubeseal controller pod
  become: false
  shell: |
    kubectl -n kube-system delete pod -l app.kubernetes.io/name=sealed-secrets