apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  labels:
    db: mysql
    project: microservices_mp4-to-mp3-converter
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /etc/data/mysql