---
- hosts: [master, workers]
  name: Install microk8s
  become: true
  tasks:
  - name: Install microk8s using snap
    community.general.snap:
      name: microk8s
      state: present
      classic: yes

- hosts: master
  name: Initialize cluster
  become: true
  roles:
  - { role: microk8s, tags: microk8s }

- hosts: master
  name: Install Helm
  become: true
  roles:
  - { role: helm-setup, tags: "helm-setup" }

- hosts: workers
  name: Join workers to the cluster
  become: true
  serial: 1
  roles:
  - { role: join-workers, tags: join-workers }

- hosts: master
  name: Deploy microservices
  roles:
  - { role: deploy-microservices, tags: deploy-microservices }

#---------- Local
- hosts: localhost
  name: change private ip to public ip in kubeconfig
  tasks:
    - name: change private ip to public ip in kubeconfig
      ansible.builtin.lineinfile:
        path: "{{ playbook_dir }}/../kube/config"
        regexp: '    server: https://.*'
        line: "    server: https://{{ hostvars[groups['master'][0]].ansible_host }}:16443"
      become: false